services:
  - type: web
    name: telegram-bot
    runtime: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://telegram-bot-XXXXX.onrender.com/webhook
